services:
  - type: web
    name: broken-oath
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
