BEGIN;

-- Entidades NPC ou do Reino não precisam pertencer a um usuário.
ALTER TABLE public.cidades
ALTER COLUMN user_id DROP NOT NULL;

ALTER TABLE public.cidades
ADD CONSTRAINT cidades_usuario_obrigatorio_para_jogador
CHECK (
    tipo_entidade <> 'jogador'
    OR user_id IS NOT NULL
);

-- Governança atual e histórica das cidades.
CREATE TABLE public.cidade_governanca (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cidade_id bigint NOT NULL
        REFERENCES public.cidades(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    tipo_governante text NOT NULL
        CHECK (tipo_governante IN ('npc', 'jogador')),

    governante_user_id uuid NULL
        REFERENCES auth.users(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    nome_governante_npc text NULL,

    titulo_governante text NOT NULL,
    nivel_governante integer NOT NULL DEFAULT 1
        CHECK (nivel_governante >= 0),

    subordinacao_tipo text NOT NULL DEFAULT 'independente'
        CHECK (
            subordinacao_tipo IN (
                'reino',
                'jogador',
                'independente'
            )
        ),

    subordinado_user_id uuid NULL
        REFERENCES auth.users(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    lealdade integer NOT NULL DEFAULT 50
        CHECK (lealdade BETWEEN 0 AND 100),

    autonomia integer NOT NULL DEFAULT 50
        CHECK (autonomia BETWEEN 0 AND 100),

    inicio_governo timestamptz NOT NULL DEFAULT now(),
    fim_governo timestamptz NULL,
    ativo boolean NOT NULL DEFAULT true,

    CONSTRAINT cidade_governanca_governante_valido CHECK (
        (
            tipo_governante = 'jogador'
            AND governante_user_id IS NOT NULL
            AND nome_governante_npc IS NULL
        )
        OR
        (
            tipo_governante = 'npc'
            AND governante_user_id IS NULL
            AND nome_governante_npc IS NOT NULL
        )
    ),

    CONSTRAINT cidade_governanca_subordinacao_valida CHECK (
        (
            subordinacao_tipo = 'jogador'
            AND subordinado_user_id IS NOT NULL
        )
        OR
        (
            subordinacao_tipo IN ('reino', 'independente')
            AND subordinado_user_id IS NULL
        )
    )
);

-- Somente uma governança ativa por cidade.
CREATE UNIQUE INDEX cidade_governanca_uma_ativa_por_cidade
ON public.cidade_governanca(cidade_id)
WHERE ativo = true;

-- Migra a governança das cidades já existentes.
INSERT INTO public.cidade_governanca (
    cidade_id,
    tipo_governante,
    governante_user_id,
    nome_governante_npc,
    titulo_governante,
    nivel_governante,
    subordinacao_tipo,
    lealdade,
    autonomia
)
SELECT
    id,
    CASE
        WHEN tipo_entidade = 'jogador' THEN 'jogador'
        ELSE 'npc'
    END,
    CASE
        WHEN tipo_entidade = 'jogador' THEN user_id
        ELSE NULL
    END,
    CASE
        WHEN tipo_entidade = 'jogador' THEN NULL
        ELSE nome_governante
    END,
    titulo_governante,
    nivel_governante,
    CASE
        WHEN tipo_entidade = 'jogador' THEN 'reino'
        ELSE 'independente'
    END,
    50,
    50
FROM public.cidades;

-- Remove a falsa propriedade de entidades NPC/Reino.
UPDATE public.cidades
SET user_id = NULL
WHERE tipo_entidade <> 'jogador';

ALTER TABLE public.cidade_governanca ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_can_read_cidade_governanca"
ON public.cidade_governanca
FOR SELECT
TO authenticated
USING (true);

COMMIT;