BEGIN;

CREATE TABLE public.entidade_tipos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    descricao text,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT entidade_tipos_nome_obrigatorio
        CHECK (length(trim(nome)) >= 3),

    CONSTRAINT entidade_tipos_nome_unico
        UNIQUE (nome)
);

INSERT INTO public.entidade_tipos (
    nome,
    descricao
)
VALUES
    ('jogador', 'Usuário humano participante do mundo.'),
    ('personagem_npc', 'Personagem não controlado diretamente por um jogador.'),
    ('cidade', 'Cidade pertencente a jogador, NPC ou Reino.'),
    ('reino', 'Autoridade central e política do mundo.');

COMMIT;