BEGIN;

CREATE TABLE public.entidades (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    entidade_tipo_id bigint NOT NULL
        REFERENCES public.entidade_tipos(id),

    referencia_uuid uuid,
    referencia_bigint bigint,

    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT entidades_referencia_valida
        CHECK (
            (referencia_uuid IS NOT NULL AND referencia_bigint IS NULL)
            OR
            (referencia_uuid IS NULL AND referencia_bigint IS NOT NULL)
        )
);

CREATE INDEX idx_entidades_tipo
    ON public.entidades(entidade_tipo_id);

CREATE INDEX idx_entidades_uuid
    ON public.entidades(referencia_uuid);

CREATE INDEX idx_entidades_bigint
    ON public.entidades(referencia_bigint);

COMMIT;