BEGIN;

CREATE TABLE public.personagem_titulos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    personagem_id bigint NOT NULL
        REFERENCES public.personagens(id)
        ON DELETE CASCADE,

    titulo_tipo_id bigint NOT NULL
        REFERENCES public.titulo_tipos(id),

    data_inicio timestamptz NOT NULL DEFAULT now(),

    data_fim timestamptz,

    ativo boolean NOT NULL DEFAULT true,

    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT personagem_titulos_periodo_valido
        CHECK (
            data_fim IS NULL
            OR data_fim >= data_inicio
        ),

    CONSTRAINT personagem_titulos_ativo_valido
        CHECK (
            (
                ativo = true
                AND data_fim IS NULL
            )
            OR
            (
                ativo = false
                AND data_fim IS NOT NULL
            )
        )
);

-- Um personagem só pode ter um título ativo por vez.
CREATE UNIQUE INDEX personagem_titulo_ativo_unico
ON public.personagem_titulos (personagem_id)
WHERE ativo = true;

CREATE INDEX idx_personagem_titulos_personagem
    ON public.personagem_titulos(personagem_id);

CREATE INDEX idx_personagem_titulos_tipo
    ON public.personagem_titulos(titulo_tipo_id);

COMMIT;