BEGIN;

CREATE TABLE public.clas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nome text NOT NULL,

    descricao text,

    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT clas_nome_obrigatorio
        CHECK (length(trim(nome)) >= 3),

    CONSTRAINT clas_nome_unico
        UNIQUE (nome)
);

COMMIT;