BEGIN;

CREATE TABLE public.cargo_tipos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nome text NOT NULL,

    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT cargo_tipos_nome_obrigatorio
        CHECK (length(trim(nome)) >= 3),

    CONSTRAINT cargo_tipos_nome_unico
        UNIQUE (nome)
);

INSERT INTO public.cargo_tipos (nome)
VALUES
    ('Governador'),
    ('Regente'),
    ('Marechal'),
    ('Capitão da Guarda'),
    ('Tesoureiro'),
    ('Chanceler'),
    ('Diplomata'),
    ('Mestre dos Espiões'),
    ('Magistrado');

COMMIT;