BEGIN;

-- =========================================================
-- 1. PROPRIEDADE DAS CIDADES
-- =========================================================

-- Cidades NPC e a Cidade Real não pertencem obrigatoriamente
-- a um usuário autenticado.
ALTER TABLE public.cidades
ALTER COLUMN user_id DROP NOT NULL;

ALTER TABLE public.cidades
DROP CONSTRAINT IF EXISTS cidades_usuario_obrigatorio_para_jogador;

ALTER TABLE public.cidades
ADD CONSTRAINT cidades_usuario_obrigatorio_para_jogador
CHECK (
    tipo_entidade <> 'jogador'
    OR user_id IS NOT NULL
);


-- =========================================================
-- 2. GOVERNANÇA DAS CIDADES
-- =========================================================

CREATE TABLE public.cidade_governanca (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cidade_id bigint NOT NULL
        REFERENCES public.cidades(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    tipo_governante text NOT NULL
        CHECK (
            tipo_governante IN (
                'npc',
                'jogador'
            )
        ),

    governante_user_id uuid NULL
        REFERENCES auth.users(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    nome_governante_npc text NULL,

    titulo_governante text NOT NULL,

    nivel_governante integer NOT NULL DEFAULT 1
        CHECK (nivel_governante >= 0),

    lealdade integer NOT NULL DEFAULT 50
        CHECK (lealdade BETWEEN 0 AND 100),

    autonomia integer NOT NULL DEFAULT 50
        CHECK (autonomia BETWEEN 0 AND 100),

    inicio_governo timestamptz NOT NULL DEFAULT now(),
    fim_governo timestamptz NULL,

    ativo boolean NOT NULL DEFAULT true,

    CONSTRAINT cidade_governanca_governante_valido
    CHECK (
        (
            tipo_governante = 'jogador'
            AND governante_user_id IS NOT NULL
            AND nome_governante_npc IS NULL
        )
        OR
        (
            tipo_governante = 'npc'
            AND governante_user_id IS NULL
            AND nome_governante_npc IS NOT NULL
        )
    ),

    CONSTRAINT cidade_governanca_periodo_valido
    CHECK (
        fim_governo IS NULL
        OR fim_governo >= inicio_governo
    )
);

-- Cada cidade pode ter somente uma governança ativa.
CREATE UNIQUE INDEX cidade_governanca_uma_ativa_por_cidade
ON public.cidade_governanca(cidade_id)
WHERE ativo = true;


-- =========================================================
-- 3. SUBORDINAÇÃO POLÍTICA DAS CIDADES
-- =========================================================

CREATE TABLE public.cidade_subordinacao (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cidade_id bigint NOT NULL
        REFERENCES public.cidades(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    tipo_suserano text NOT NULL DEFAULT 'independente'
        CHECK (
            tipo_suserano IN (
                'reino',
                'jogador',
                'independente'
            )
        ),

    suserano_user_id uuid NULL
        REFERENCES auth.users(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    inicio_subordinacao timestamptz NOT NULL DEFAULT now(),
    fim_subordinacao timestamptz NULL,

    motivo text NULL,

    ativo boolean NOT NULL DEFAULT true,

    CONSTRAINT cidade_subordinacao_suserano_valido
    CHECK (
        (
            tipo_suserano = 'jogador'
            AND suserano_user_id IS NOT NULL
        )
        OR
        (
            tipo_suserano IN ('reino', 'independente')
            AND suserano_user_id IS NULL
        )
    ),

    CONSTRAINT cidade_subordinacao_periodo_valido
    CHECK (
        fim_subordinacao IS NULL
        OR fim_subordinacao >= inicio_subordinacao
    )
);

-- Cada cidade pode ter somente uma subordinação ativa.
CREATE UNIQUE INDEX cidade_subordinacao_uma_ativa_por_cidade
ON public.cidade_subordinacao(cidade_id)
WHERE ativo = true;


-- =========================================================
-- 4. MIGRAÇÃO DAS CIDADES EXISTENTES
-- =========================================================

INSERT INTO public.cidade_governanca (
    cidade_id,
    tipo_governante,
    governante_user_id,
    nome_governante_npc,
    titulo_governante,
    nivel_governante,
    lealdade,
    autonomia
)
SELECT
    id,

    CASE
        WHEN tipo_entidade = 'jogador'
            THEN 'jogador'
        ELSE 'npc'
    END,

    CASE
        WHEN tipo_entidade = 'jogador'
            THEN user_id
        ELSE NULL
    END,

    CASE
        WHEN tipo_entidade = 'jogador'
            THEN NULL
        ELSE COALESCE(nome_governante, 'Governante desconhecido')
    END,

    COALESCE(titulo_governante, 'Governante'),
    COALESCE(nivel_governante, 1),

    50,
    50

FROM public.cidades;


INSERT INTO public.cidade_subordinacao (
    cidade_id,
    tipo_suserano,
    suserano_user_id
)
SELECT
    id,

    CASE
        WHEN tipo_entidade = 'jogador'
            THEN 'reino'
        ELSE 'independente'
    END,

    NULL

FROM public.cidades;


-- Cidades NPC e a Cidade Real não possuem proprietário.
UPDATE public.cidades
SET user_id = NULL
WHERE tipo_entidade <> 'jogador';


-- =========================================================
-- 5. SEGURANÇA RLS
-- =========================================================

ALTER TABLE public.cidade_governanca
ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_can_read_cidade_governanca"
ON public.cidade_governanca
FOR SELECT
TO authenticated
USING (true);


ALTER TABLE public.cidade_subordinacao
ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_can_read_cidade_subordinacao"
ON public.cidade_subordinacao
FOR SELECT
TO authenticated
USING (true);


COMMIT;