BEGIN;

CREATE TABLE public.personagens_npc (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nome text NOT NULL,

    apelido text,

    cidade_origem_id bigint
        REFERENCES public.cidades(id),

    coragem smallint NOT NULL DEFAULT 50,

    respeito smallint NOT NULL DEFAULT 50,

    honra smallint NOT NULL DEFAULT 50,

    ambicao smallint NOT NULL DEFAULT 50,

    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT personagens_npc_nome_obrigatorio
        CHECK (length(trim(nome)) >= 3),

    CONSTRAINT personagens_npc_nome_unico
        UNIQUE (nome),

    CONSTRAINT personagens_npc_coragem_valida
        CHECK (coragem BETWEEN 0 AND 100),

    CONSTRAINT personagens_npc_respeito_valido
        CHECK (respeito BETWEEN 0 AND 100),

    CONSTRAINT personagens_npc_honra_valida
        CHECK (honra BETWEEN 0 AND 100),

    CONSTRAINT personagens_npc_ambicao_valida
        CHECK (ambicao BETWEEN 0 AND 100)
);

CREATE INDEX idx_personagens_npc_cidade_origem
    ON public.personagens_npc(cidade_origem_id);

COMMIT;