BEGIN;

CREATE TABLE public.personagem_cargos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    personagem_id bigint NOT NULL
        REFERENCES public.personagens(id),

    cargo_tipo_id bigint NOT NULL
        REFERENCES public.cargo_tipos(id),

    entidade_id bigint NOT NULL
        REFERENCES public.entidades(id),

    data_inicio timestamptz NOT NULL DEFAULT now(),

    data_fim timestamptz,

    ativo boolean NOT NULL DEFAULT true,

    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT personagem_cargos_periodo_valido
        CHECK (
            data_fim IS NULL
            OR data_fim >= data_inicio
        ),

    CONSTRAINT personagem_cargos_ativo_valido
        CHECK (
            (ativo = true AND data_fim IS NULL)
            OR
            (ativo = false AND data_fim IS NOT NULL)
        )
);

CREATE UNIQUE INDEX personagem_cargos_ativo_unico
ON public.personagem_cargos (
    personagem_id,
    cargo_tipo_id,
    entidade_id
)
WHERE ativo = true;

CREATE INDEX idx_personagem_cargos_personagem
    ON public.personagem_cargos(personagem_id);

CREATE INDEX idx_personagem_cargos_entidade
    ON public.personagem_cargos(entidade_id);

CREATE INDEX idx_personagem_cargos_tipo
    ON public.personagem_cargos(cargo_tipo_id);

COMMIT;