BEGIN;

CREATE TABLE public.sentimento_tipos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT sentimento_tipos_nome_obrigatorio
        CHECK (length(trim(nome)) >= 3),

    CONSTRAINT sentimento_tipos_nome_unico
        UNIQUE (nome)
);

INSERT INTO public.sentimento_tipos (nome)
VALUES
    ('Lealdade'),
    ('Confiança'),
    ('Empatia'),
    ('Respeito'),
    ('Medo'),
    ('Admiração'),
    ('Rivalidade');

COMMIT;