BEGIN;

CREATE TABLE public.titulo_tipos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nome text NOT NULL,

    ordem smallint NOT NULL,

    categoria text NOT NULL,

    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT titulo_tipos_nome_obrigatorio
        CHECK (length(trim(nome)) >= 3),

    CONSTRAINT titulo_tipos_nome_unico
        UNIQUE (nome),

    CONSTRAINT titulo_tipos_ordem_unica
        UNIQUE (ordem),

    CONSTRAINT titulo_tipos_ordem_valida
        CHECK (ordem >= 0),

    CONSTRAINT titulo_tipos_categoria_valida
        CHECK (
            categoria IN (
                'negativo',
                'nobre',
                'real'
            )
        )
);

INSERT INTO public.titulo_tipos (
    nome,
    ordem,
    categoria
)
VALUES
    ('Renegado', 0, 'negativo'),
    ('Barão', 1, 'nobre'),
    ('Visconde', 2, 'nobre'),
    ('Conde', 3, 'nobre'),
    ('Marquês', 4, 'nobre'),
    ('Duque', 5, 'nobre'),
    ('Príncipe', 6, 'real'),
    ('Rei', 7, 'real');

COMMIT;