BEGIN;

CREATE TABLE public.sentimentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    origem_entidade_id bigint NOT NULL
        REFERENCES public.entidades(id)
        ON DELETE CASCADE,

    destino_entidade_id bigint NOT NULL
        REFERENCES public.entidades(id)
        ON DELETE CASCADE,

    sentimento_tipo_id bigint NOT NULL
        REFERENCES public.sentimento_tipos(id),

    valor smallint NOT NULL DEFAULT 50,

    created_at timestamptz NOT NULL DEFAULT now(),

    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT sentimentos_valor_valido
        CHECK (valor BETWEEN 0 AND 100),

    CONSTRAINT sentimentos_origem_destino_diferentes
        CHECK (origem_entidade_id <> destino_entidade_id),

    CONSTRAINT sentimentos_unico
        UNIQUE (
            origem_entidade_id,
            destino_entidade_id,
            sentimento_tipo_id
        )
);

CREATE INDEX idx_sentimentos_origem
    ON public.sentimentos(origem_entidade_id);

CREATE INDEX idx_sentimentos_destino
    ON public.sentimentos(destino_entidade_id);

CREATE INDEX idx_sentimentos_tipo
    ON public.sentimentos(sentimento_tipo_id);

COMMIT;